# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Musings
tagline:          'Random things I like'
description:      ''
url:              http://shenw123.github.io

author:
  name:           'Shen Wang'
  url:            

gems:             [jekyll-paginate, jekyll-gist]
paginate:         5


# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
